 
name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        build_type: [debug, release]

    runs-on: ${{ matrix.os }}

    env:
      CARGO_BUILD_FLAGS: ${{ matrix.build_type == 'release' && '--release' || '' }}

    steps:
      - uses: actions/checkout@v3
        with:
            submodules: recursive
            fetch-depth: 0

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install Clang-18 on Ubuntu
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gnupg software-properties-common
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 18

      - name: Install Clang on Windows
        if: runner.os == 'Windows'
        shell: powershell
        run: |
          choco install llvm -y
          echo "LIBCLANG_PATH=C:\Program Files\LLVM\bin" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Build
        run: cargo build --manifest-path resourcelib-ffi/Cargo.toml $CARGO_BUILD_FLAGS
